# Generated by Django 3.1.2 on 2020-11-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0002_auto_20201109_1607'),
        ('stay', '0003_auto_20201110_1257'),
    ]

    operations = [
    ]
