# Generated by Django 3.1.2 on 2020-11-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stay', '0001_initial'),
        ('user', '0002_auto_20201104_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(auto_now=True)),
                ('body', models.CharField(max_length=2000)),
                ('cleanliness_star', models.IntegerField()),
                ('communication_star', models.IntegerField()),
                ('checkin_star', models.IntegerField()),
                ('accuracy_star', models.IntegerField()),
                ('location_star', models.IntegerField()),
                ('value_star', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.host')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stay.stay')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
