# Generated by Django 3.1.2 on 2020-11-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20201109_2318'),
        ('review', '0002_auto_20201109_1607'),
    ]

    operations = [
    ]
